---
abstract: 'Maintain and serve a REST API to search PGXN mirrors'
author:
  - 'David E. Wheeler <david.wheeler@pgexperts.com>'
build_requires:
  Module::Build: 0.30
  Software::License: 0.102340
  Test::Exception: 0.31
  Test::File: 1.29
  Test::File::Contents: 0.20
  Test::MockModule: 0.05
  Test::More: 0.70
  Test::Output: 0.16
configure_requires:
  Module::Build: 0.30
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.110930'
license: open_source
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PGXN-API
provides:
  PGXN::API:
    file: lib/PGXN/API.pm
    version: v0.15.0
  PGXN::API::Indexer:
    file: lib/PGXN/API/Indexer.pm
    version: v0.15.0
  PGXN::API::Router:
    file: lib/PGXN/API/Router.pm
    version: v0.15.0
  PGXN::API::Sync:
    file: lib/PGXN/API/Sync.pm
    version: v0.15.0
recommends:
  Test::Pod: 1.41
  Test::Pod::Coverage: 1.06
requires:
  Archive::Zip: 1.30
  Cwd: 3.33
  Data::Dump: 1.17
  Digest::SHA1: 2.13
  Email::MIME::Creator: 1.905
  Email::Sender::Simple: 0.102370
  File::Copy::Recursive: 0.38
  File::Path: 2.08
  File::Spec: 3.33
  JSON: 2.27
  JSON::XS: 2.3
  KinoSearch: 0.311
  List::MoreUtils: 0.30
  List::Util: 1.23
  Moose: 1.15
  Moose::Util::TypeConstraints: 1.15
  MooseX::Singleton: 0.25
  PGXN::API::Searcher: v0.9.0
  Plack: 0.9977
  Plack::App::Directory: 0
  Plack::App::File: 0
  Plack::Builder: 0
  Plack::Middleware::JSONP: 0
  Text::Markup: 0.12
  URI::Template: 0.15
  XML::LibXML: 1.70
  namespace::autoclean: 0.11
  perl: 5.01
resources:
  bugtracker: http://github.com/theory/pgxn-api/issues/
  homepage: http://api.pgxn.org/
  license: http://www.opensource.org/licenses/postgresql
  repository: http://github.com/theory/pgxn-api/tree/
version: v0.15.0
